# Generated by Django 3.2.5 on 2021-09-27 13:30

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_portfolio_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='reel_content',
            field=wagtail.core.fields.StreamField([('Reels', wagtail.core.blocks.StructBlock([('reel_video_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('reel_video_link', wagtail.core.blocks.CharBlock())]))], null=True),
        ),
    ]
