# Generated by Django 3.2.8 on 2021-10-22 12:00

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210928_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='homePage_partners_description',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='homePage_partners_subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='homePage_partners_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='partners_content',
            field=wagtail.core.fields.StreamField([('Partners', wagtail.core.blocks.StructBlock([('partners_logo', wagtail.images.blocks.ImageChooserBlock(required=False))]))], null=True),
        ),
    ]
