# Generated by Django 3.2.8 on 2021-11-10 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20211022_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='reel_content',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='reels_big_video_id',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='reels_big_video_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='reels_big_video_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='reels_big_video_target',
        ),
    ]
