# Generated by Django 3.2.8 on 2021-11-10 13:46

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20211110_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='homePage_second_Title',
            new_name='homePage_services_subTitle',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='homePage_second_subTitle',
            new_name='homePage_services_title',
        ),
        migrations.AddField(
            model_name='homepage',
            name='homePage_services_content',
            field=wagtail.core.fields.StreamField([('Card', wagtail.core.blocks.StructBlock([('card_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('card_title', wagtail.core.blocks.CharBlock())]))], null=True),
        ),
    ]
