# Generated by Django 3.2.8 on 2021-11-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20211110_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='homePage_first_secondSubTitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
