# Generated by Django 3.2.5 on 2021-10-04 09:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('showreel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommercialPage',
            new_name='ShowreelDetailPage',
        ),
        migrations.RenameModel(
            old_name='DocumentPage',
            new_name='ShowreelListingPage',
        ),
        migrations.RenameField(
            model_name='showreeldetailpage',
            old_name='com_title',
            new_name='doc_title',
        ),
        migrations.RenameField(
            model_name='showreellistingpage',
            old_name='doc_title',
            new_name='com_title',
        ),
    ]
