# Generated by Django 3.2.5 on 2021-10-04 11:59

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('showreel', '0002_auto_20211004_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showreeldetailpage',
            old_name='doc_title',
            new_name='big_image_id',
        ),
        migrations.RenameField(
            model_name='showreellistingpage',
            old_name='com_title',
            new_name='listing_title',
        ),
        migrations.AddField(
            model_name='showreeldetailpage',
            name='detail_big_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='showreeldetailpage',
            name='detail_big_image_description',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='showreeldetailpage',
            name='detail_big_image_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='showreeldetailpage',
            name='detail_big_image_video_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='showreeldetailpage',
            name='detail_big_image_video_target',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='showreeldetailpage',
            name='detail_content',
            field=wagtail.core.fields.StreamField([('Detail', wagtail.core.blocks.StructBlock([('detail_video_id', wagtail.core.blocks.CharBlock()), ('detail_video_target', wagtail.core.blocks.CharBlock()), ('detail_video_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('detail_video_link', wagtail.core.blocks.CharBlock()), ('detail_video_title', wagtail.core.blocks.CharBlock()), ('detail_video_description', wagtail.core.blocks.RichTextBlock())]))], null=True),
        ),
        migrations.AddField(
            model_name='showreeldetailpage',
            name='detail_description',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='showreeldetailpage',
            name='detail_subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='showreeldetailpage',
            name='detail_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
