# Generated by Django 3.2.8 on 2021-11-10 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showreel', '0003_auto_20211004_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showreeldetailpage',
            name='big_image_id',
        ),
        migrations.RemoveField(
            model_name='showreeldetailpage',
            name='detail_big_image',
        ),
        migrations.RemoveField(
            model_name='showreeldetailpage',
            name='detail_big_image_description',
        ),
        migrations.RemoveField(
            model_name='showreeldetailpage',
            name='detail_big_image_title',
        ),
        migrations.RemoveField(
            model_name='showreeldetailpage',
            name='detail_big_image_video_link',
        ),
        migrations.RemoveField(
            model_name='showreeldetailpage',
            name='detail_big_image_video_target',
        ),
    ]
