# Generated by Django 3.2.8 on 2021-11-10 12:35

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('showreel', '0004_auto_20211110_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showreeldetailpage',
            name='detail_content',
            field=wagtail.core.fields.StreamField([('Detail', wagtail.core.blocks.StructBlock([('detail_video_id', wagtail.core.blocks.CharBlock()), ('detail_video_target', wagtail.core.blocks.CharBlock()), ('detail_video_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('detail_video_link', wagtail.core.blocks.CharBlock()), ('detail_video_title', wagtail.core.blocks.CharBlock())]))], null=True),
        ),
    ]
