# Generated by Django 3.2.5 on 2021-09-29 13:36

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('about_title', models.CharField(blank=True, max_length=200, null=True)),
                ('about_subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('first_about_title', models.CharField(blank=True, max_length=200, null=True)),
                ('first_about_description', wagtail.core.fields.RichTextField(null=True)),
                ('second_about_title', models.CharField(blank=True, max_length=200, null=True)),
                ('second_about_subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('second_about_description', wagtail.core.fields.RichTextField(null=True)),
                ('services_content', wagtail.core.fields.StreamField([('services', wagtail.core.blocks.StructBlock([('service_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('service_title', wagtail.core.blocks.CharBlock()), ('service_description', wagtail.core.blocks.RichTextBlock())]))], null=True)),
                ('third_about_title', models.CharField(blank=True, max_length=200, null=True)),
                ('other_services_content', wagtail.core.fields.StreamField([('other_services', wagtail.core.blocks.StructBlock([('service_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('service_title', wagtail.core.blocks.CharBlock()), ('service_description', wagtail.core.blocks.RichTextBlock())]))], null=True)),
                ('first_about_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
