# Generated by Django 3.2.8 on 2021-11-12 09:01

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatWeCanDo',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_title', models.CharField(blank=True, max_length=200, null=True)),
                ('page_subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('page_second_title', models.CharField(blank=True, max_length=200, null=True)),
                ('cards_content', wagtail.core.fields.StreamField([('cards', wagtail.core.blocks.StructBlock([('cards_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('cards_title', wagtail.core.blocks.CharBlock()), ('cards_description', wagtail.core.blocks.RichTextBlock())]))], null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
